vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.autoindent = true
vim.opt.fillchars = "eob: "
vim.opt.numberwidth = 4
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.wrap = false
vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.opt.signcolumn = "yes"
vim.opt.backspace = "indent,eol,start"
vim.opt.clipboard:append("unnamedplus")
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.cursorline = true
vim.opt.hlsearch = false
vim.opt.scrolloff = 10
vim.o.pumborder = "single"
vim.o.pumheight = 12
vim.o.completeopt = "menuone,noselect"
vim.o.completeitemalign = "abbr,kind,menu"
